name: Build
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        java: [21]
        modLoaders: [fabric]

    steps:
    - uses: actions/checkout@v4
    - name: Register custom runtimes from GraalVM
      uses: graalvm/setup-graalvm@v1
      if: matrix.java >= 21
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.9.3
      with:
        gradle-version: 8.10.2
    - name: Run game test
      run: ./gradlew runClient --stacktrace
    - name: Build
      run: ./gradle-wrapper/gradlew build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if: matrix.java == '21'
      with:
        name: Artifacts-${{ matrix.modLoaders }}
        path: build/libs/
